// アプリの初期描画設定。
// src-tauri の RenderSettings::default() および settings.json 未作成時の既定と一致させること。
// どちらかを変えたら、もう一方とリセット値・Visual QA の base も更新する。
export const DEFAULT_RENDER_SETTINGS = {
  showDesktopPreview: true,
  autoTextureSize: true,
  width: 1024,
  height: 256,
  maxTextureWidth: 4096,
  maxTextureHeight: 4096,
  renderScale: 1,
  overlayMaxFps: 30,
  overlayPrepareMs: 900,
  overlayWidthMeters: 1.45,
  fontSize: 53,
  fontSizePercent: 100,
  rubyEnabled: true,
  rubyDistance: 6,
  vrchatChatboxEnabled: false,
  vrchatChatboxHost: "127.0.0.1",
  vrchatChatboxPort: 9000,
  textColor: "#ffffff",
  textOpacityPercent: 100,
  backgroundEnabled: true,
  backgroundColor: "#000000",
  backgroundOpacityPercent: 90,
  backgroundPadding: 22,
  outlineEnabled: false,
  outlineColor: "#000000",
  outlineWidth: 8,
  shadowEnabled: false,
  shadowColor: "#000000",
  shadowBlur: 0,
  positionX: 0,
  positionY: -0.3,
  positionZ: -1.2,
  rotationX: -8,
  rotationY: 0,
  rotationZ: 0,
  textOffsetX: 0,
  textOffsetY: 0,
  theme: "live",
};

export const DEFAULT_PLAYBACK_SETTINGS = {
  mode: "countdown",
  countdownSeconds: 10,
  targetTime: "23:00",
};
