// UIラベル。画面文言はここだけを参照する。
export const ui = {
  // --- アプリ共通 / ワークスペース ---
  appName: "CaptioLinkVR",
  appSubtitle: "字幕表示ツール",
  license: "ライセンス",
  licenseDisclaimer:
    "CaptioLinkVR は Valve Corporation / SteamVR、および VRChat Inc. とは無関係の個人制作の非公式ツールです。各社の公式製品・公式サポートではありません。",
  licenseSummaryTitle: "本アプリのライセンス概要",
  licenseSummaryBody:
    "ソースコードは MIT License です（MIT の範囲での利用・再配布が可能です）。ロゴ・ブランド画像は著作者の著作物であり、無断での利用・転載はできません。同梱字幕プリセット（captions/）は各原著作権者に帰属し、無断転載・再配布・改変・翻案・商用利用はできません（条件の正文は captions/LICENSE.md の日本語です）。captions/ およびブランド資産について、リポジトリのクローンや閲覧をもって再配布・ミラー・別配布の権利が付与されるものではありません。",
  licenseThirdPartyTitle: "第三者ライセンス",
  close: "閉じる",
  footerLabel: "フッター",
  createdBy: "Produced by",
  creatorName: "Shiina Sakamoto",
  affiliationName: "Shiinarium",
  affiliationOf: "Affiliation",
  footerNoteLabel: "From the maker",
  footerNoteBody:
    "字幕表示プロジェクトは、ワールド制作者様、および台詞・楽曲制作者様のご協力のもと、無償・非営利で運営されています。プリセット字幕データの著作権は本プロジェクトにはなく、それぞれの制作者様に帰属します。",
  footerWorldsCta: "字幕対応ワールドの相談・募集",
  openWorldsForm: "字幕対応ワールドの相談・募集を開く",
  openX: "X（旧Twitter）を開く",
  openGitHub: "GitHubリポジトリを開く",
  booth: "Booth",
  openBooth: "Boothを開く",
  advancedOpen: "高度な設定を開く",
  advancedClose: "高度な設定を閉じる",
  resetVrSettings: "VR設定を初期化",
  resetStyleSettings: "字幕スタイルを初期化",
  countdownMode: "カウントダウンモード",
  manualCount: "指定カウント",
  targetTime: "指定時刻",
  playing: "再生中",
  play: "カウントダウンを開始する",
  noSubtitle: "字幕が選択されていません",
  stop: "停止",
  startCount: "開始カウント",
  countdownSecondsOption: (seconds) => `${seconds}秒`,
  startTime: "開始時刻",
  hour: "時間",
  minute: "分",
  adjustMinuteUnit: "1分",
  adjustSecondUnit: "1秒",
  style: "字幕スタイル",
  position: "位置",
  rotation: "回転",
  textSize: (percent) => `字幕サイズ（ ${percent}% ）`,
  wrapWidth: (percent) => `折り返し幅（ ${percent}% ）`,
  wrapWidthDescription:
    "長い字幕を自動で折り返す幅です。小さくするほど視界内に収まりやすく、大きくするほど1行が長くなります。",
  subtitleQuality: (scale) => `字幕画質（ ${parseFloat(Number(scale).toFixed(2))}倍 ）`,
  subtitleQualityDescription:
    "基準の描画倍率です。距離に応じて解像度を自動加減し、遠いときは負荷を抑えつつ見た目の画質を保ちます。",
  overlayMaxFps: (fps) => `VR更新FPS（ ${fps} ）`,
  ruby: "ルビ",
  background: "背景",
  shadow: "影",
  outline: "袋文字",
  featureOn: "オン",
  featureOff: "オフ",
  textColorLabel: (value) => `文字色（ ${value} ）`,
  textOpacityLabel: (percent) => `字幕の透過（ ${percent}% ）`,
  textOpacityDescription: "字幕全体の不透明度です。背景の透過もこの値を基準にします。",
  rubyDistanceLabel: (value) => `本文とのルビの距離（ ${value} ）`,
  backgroundColorLabel: (value) => `背景色（ ${value} ）`,
  backgroundOpacityPercentLabel: (percent) => `背景の透過（ ${percent}% ）`,
  backgroundOpacityPercentDescription: "字幕の透過を 100% としたときの背景の不透明度です。",
  backgroundPaddingLabel: (value) => `背景の大きさ（余白）（ ${value} ）`,
  outlineColorLabel: (value) => `袋文字色（ ${value} ）`,
  outlineWidthLabel: (value) => `袋文字の大きさ（ ${value} ）`,
  colorPresets: "プリセット",
  colorCustom: "カスタム",
  colorPresetOption: (kind, name) => `${kind}: ${name}`,
  textColorKind: "文字色",
  backgroundColorKind: "背景色",
  outlineColorKind: "袋文字色",
  shadowBlurLabel: (value) => `影の太さ（ ${value} ）`,
  preview: "字幕プレビュー",
  previewDisclaimer:
    "実際の見た目とは異なるので、位置や大きさなどはVR画面で確認してください。",
  cue: "字幕キュー",
  notSelected: "未選択",
  playFromHere: "この行から再生",
  empty: "SRT / ASSA を読み込むと字幕一覧が表示されます",
  connected: "SteamVR オーバーレイ接続中",
  steamVrWaiting: "SteamVR 起動待機中",
  desktopMode: "SteamVR接続なし（デスクトップモード）",
  steamVrLaunchWaiting: "SteamVRの起動待ち",
  cuePage: "字幕一覧",
  vrPage: "VR設定",
  sendSample: "字幕テスト送信",
  stopSample: "字幕テスト停止",
  sampleTexts: [
    "字幕の{表示|ひょうじ}テストです。",
    "もし見にくければ、{位置|いち}や{文字色|もじしょく}などを確認しながら、VR設定や字幕スタイルを{調節|ちょうせつ}してください。",
    "もし見にくければ、{位置|いち}や{文字色|もじしょく}などを確認しながら、VR設定や字幕スタイルを{調節|ちょうせつ}してください。",
    "長文でも読みやすい幅に収まるように、折り返し幅を{調節|ちょうせつ}してください。",
    "長文でも読みやすい幅に収まるように、折り返し幅を{調節|ちょうせつ}してください。",
  ],
  vrchatChatbox: "VRChatチャットボックスにも送信",
  yAxis: "Y軸（上下）",
  xAxis: "X軸（左右）",
  zAxis: "Z軸（前後）",
  rotateX: "X軸の回転",
  rotateY: "Y軸の回転",
  rotateZ: "Z軸の回転",
  visualQaStart: "目視チェックを実行",
  visualQaStop: "目視チェックを停止",
  visualQaLocked: "再生中は実行できません",
  visualQaStepLabel: (index, count, label) => `${index}/${count} ${label}`,
  visualQaSpeed: (speed) => `${speed}倍`,
  visualQaSpeedLabel: "速さ",
  visualQaLoop: "くり返す",
  visualQaBlockLabel: "チェック範囲",
  visualQaBlockAll: "すべて",

  // --- プリセット / 字幕ソース ---
  fileSelect: "ファイル選択",
  presetSelect: "プリセット",
  presetPlaceholder: "字幕を選択してください",
  customPreset: "カスタム",
  presetPickerCustomHint: "SRT / ASS / ASSA ファイルを選択",
  presetPickerMetaLoading: "プリセット情報を読み込み中...",
  clear: "ファイルクリア",
  presetLoaded: "プリセット字幕を読み込みました",
  presetLoadFailed: "プリセット字幕の読み込みに失敗しました",
  presetLoading: "プリセット字幕を読み込み中...",
  presetListFailed: "プリセット一覧の取得に失敗しました",
  presetMetaFailed: "プリセット情報の取得に失敗しました",
  presetOpenDescription: "説明文を開く",
  presetCloseDescription: "説明文を閉じる",
  worldName: "ワールド名",
  verifiedAt: "最終動作確認日",
  supervisor: "字幕監修",
  editor: "字幕制作",
  usageSummary: "使い方",
  usageStartTiming: "開始タイミング",
  worldLink: "ワールドリンク",
  openGuideVideo: "説明動画を見る",
  fileLoaded: "字幕ファイルを読み込みました",
  presetLockedWhilePlaying: "再生中は変更できません。停止してから選び直してください。",

  // --- 設定の読み込み ---
  settingsLoadFailed: "設定データの読み込みに失敗しました。",
  settingsLoadResetAll: "設定は初期値で設定し直されました。",
  settingsLoadResetFields: (labels) =>
    `該当箇所（${labels.join("、")}）は初期値で設定し直されました。`,
  dismissNotice: "通知を閉じる",

  // --- アップデート ---
  updateAction: "アップデート",
  updateConfirmTitle: "アップデートの確認",
  updateLaunching: "起動中...",
  updateFailed: "アップデートの開始に失敗しました",
  updateFailedUnknown: "原因不明のエラーが発生しました",
  updateCheckFailed: "アップデートの確認に失敗しました",
  cancel: "キャンセル",
  updateAvailable: (version) => `新しいバージョン v${version} が利用可能です`,
  updateConfirmBody: (current, next) =>
    `v${current} から v${next} へ更新します。アプリを終了し、更新処理が続行されます。`,
};
